Repository Stageus/AIrena-backend, pull requests merged in 2025-03, with the labels that each got.

#24 [SUS-52] 유효성 검증
  src/core/util/EmailSender/index.ts
  src/core/util/EmailSender/templates/confirmSignupMail.html
  src/core/util/Regex/index.ts
  src/like/entity/dao/frontend/request/path/ArticleIdxPath.ts
  src/member/entity/dao/frontend/request/FindIdRequest.ts
  src/member/entity/dao/frontend/request/FindPasswordRequest.ts
  src/member/entity/dao/frontend/request/NicknameChangeRequest.ts
  src/member/entity/dao/frontend/request/NormalLoginRequest.ts
  src/member/entity/dao/frontend/request/PasswordChangeRequest.ts
  src/member/entity/dao/frontend/request/SendFindPasswordEmailRequest.ts
  src/member/entity/dao/frontend/request/SendVerifyEmailRequest.ts
  src/member/entity/dao/frontend/request/SignupRequest.ts
  src/mock/entity/dao/frontend/request/body/MockEditRequest.ts
  src/mock/entity/dao/frontend/request/body/QuizRequest.ts
  src/mock/entity/dao/frontend/request/body/SolveRequest.ts
  src/mock/entity/dao/frontend/request/body/WriteRequest.ts
  src/mock/entity/dao/frontend/request/path/MockIdxPath.ts
  src/mock/entity/dao/frontend/request/path/QuizIdxPath.ts
  src/notice/entity/dao/frontend/request/ListRequest.ts
  src/notice/entity/dao/frontend/request/ListSearchRequest.ts
  src/notice/entity/dao/frontend/request/NoticeEditBodyRequest.ts
  src/notice/entity/dao/frontend/request/NoticePathRequest.ts
  src/notice/entity/dao/frontend/request/WriteRequest.ts
  src/rank/entity/dao/request/FilteredRankListRequest.ts
  src/rank/entity/dao/request/RankListRequest.ts
Labels: 기능 구현

#25 [SUS-71] CD 설정
  .github/workflows/prod_deploy.yml
Labels: 환경 설정

#26 [SUS-72] 입력값 제한 수정
  src/member/entity/dao/frontend/request/FindIdRequest.ts
  src/member/entity/dao/frontend/request/FindPasswordRequest.ts
  src/member/entity/dao/frontend/request/NormalLoginRequest.ts
  src/mock/entity/dao/frontend/request/query/ListRequest.ts
  src/mock/entity/dao/frontend/request/query/SearchRequest.ts
  src/notice/entity/dao/frontend/request/ListSearchRequest.ts
  src/rank/entity/dao/request/FilteredRankListRequest.ts
Labels: 기능 구현

#30 [SUS-76] 엔드 포인트 리팩터링
  package-lock.json
  package.json
  src/core/util/Regex/index.ts
  src/like/router/addRouter.ts
  src/like/router/index.ts
  src/like/router/likeItemRouter.ts
  src/mock/entity/dao/frontend/request/query/ListRequest.ts
  src/mock/router/index.ts
  src/mock/router/listRouter.ts
  src/mock/router/mockItemRouter.ts
  src/mock/router/writeRouter.ts
  src/mock/service/ListService.ts
  src/notice/entity/dao/frontend/request/ListRequest.ts
  src/notice/entity/dao/frontend/response/ListResponse.ts
  src/notice/entity/dao/frontend/response/ListSearchResponse.ts
  src/notice/entity/dto/NoticeList.ts
  src/notice/router/index.ts
  src/notice/router/listRouter.ts
  src/notice/router/noticeItemRouter.ts
  src/notice/router/writeRouter.ts
  src/notice/service/ListService.ts
  src/notice/service/NoticeItemService.ts
  src/notice/service/WriteService.ts
  src/rank/entity/dao/request/RankListRequest.ts
  src/rank/router/rankListRouter.ts
  src/rank/service/rankListService.ts
Labels: 리팩터링

#32 [SUS-78] 정규표현식 검증 수정
  src/member/entity/dao/frontend/request/NicknameChangeRequest.ts
  src/member/entity/dao/frontend/request/PasswordChangeRequest.ts
  src/member/entity/dao/frontend/request/SendFindPasswordEmailRequest.ts
  src/member/entity/dao/frontend/request/SendVerifyEmailRequest.ts
  src/member/entity/dao/frontend/request/SignupRequest.ts
  src/mock/entity/dao/frontend/request/body/MockEditRequest.ts
  src/mock/entity/dao/frontend/request/body/QuizRequest.ts
  src/mock/entity/dao/frontend/request/body/WriteRequest.ts
  src/mock/entity/dao/frontend/request/path/MockIdxPath.ts
  src/mock/entity/dao/frontend/request/path/QuizIdxPath.ts
  src/notice/entity/dao/frontend/request/NoticeEditBodyRequest.ts
  src/notice/entity/dao/frontend/request/NoticePathRequest.ts
  src/notice/entity/dao/frontend/request/WriteRequest.ts
  src/rank/entity/dao/request/FilteredRankListRequest.ts
  src/rank/entity/dao/request/RankListRequest.ts
Labels: 리팩터링

#35 [SUS-82] 프론트엔드 연동 간 수정
  .sql/.sql
  index.ts
  src/core/util/Regex/index.ts
  src/core/util/multipartParser/index.ts
  src/like/entity/dao/frontend/request/path/ArticleIdxPath.ts
  src/like/router/index.ts
  src/like/router/likeItemRouter.ts
  src/member/entity/dao/db/ProfileResultFromDB.ts
  src/member/entity/dao/frontend/response/ProfileResponse.ts
  src/member/repository/MemberInfoRepository.ts
  src/member/service/ChangeService.ts
  src/member/service/MeService.ts
  src/mock/entity/dao/frontend/request/body/MockEditRequest.ts
  src/mock/entity/dao/frontend/request/body/WriteRequest.ts
  src/mock/entity/dao/frontend/request/path/QuizIdxPath.ts
  src/mock/entity/dao/frontend/response/DetailResponse.ts
  src/mock/entity/dao/frontend/response/ListResponse.ts
  src/mock/entity/dto/MockList.ts
  src/mock/repository/MockRepository.ts
  src/mock/service/ListService.ts
  src/mock/service/MockItemService.ts
  src/notice/entity/dao/frontend/request/NoticeEditBodyRequest.ts
  src/notice/entity/dao/frontend/request/WriteRequest.ts
  src/notice/repository/NoticeRepository.ts
  src/notice/service/NoticeItemService.ts
  src/rank/entity/dao/request/FilteredRankListRequest.ts
  src/rank/repository/rankListRepository.ts
  src/rank/service/rankListService.ts
Labels: 기능 구현, 리팩터링

#33 [SUS-81] 쿼리 반환 날짜 형식 수정
  src/notice/repository/NoticeRepository.ts
Labels: 리팩터링

#34 [SUS-83] 공지사항 dao 추가 및 수정
  src/notice/entity/dao/db/NoticeInfoFromDB.ts
  src/notice/entity/dao/db/NoticeListFromDB.ts
  src/notice/entity/dao/frontend/response/ListResponse.ts
  src/notice/repository/NoticeRepository.ts
  src/notice/service/ListService.ts
Labels: 리팩터링

#36 [SUS-84] 요구사항 명세서와 request dto 통일
  src/core/error/ErrorRegistry.ts
  src/core/util/Regex/index.ts
  src/core/util/multipartParser/index.ts
  src/member/entity/dao/frontend/request/FindIdRequest.ts
  src/member/entity/dao/frontend/request/FindPasswordRequest.ts
  src/member/entity/dao/frontend/request/NormalLoginRequest.ts
  src/mock/entity/dao/frontend/request/body/MockEditRequest.ts
  src/mock/entity/dao/frontend/request/body/SolveRequest.ts
  src/mock/entity/dao/frontend/request/body/WriteRequest.ts
  src/mock/service/ListService.ts
  src/mock/service/WriteService.ts
  src/notice/entity/dao/frontend/request/NoticeEditBodyRequest.ts
  src/notice/entity/dao/frontend/request/WriteRequest.ts
  src/rank/entity/dao/request/RankListRequest.ts
Labels: 리팩터링

#38 [SUS-85] 모의고사 결과 응답 dto 수정
  src/mock/entity/dao/frontend/response/ResultResponse.ts
  src/mock/service/MockItemService.ts
Labels: 리팩터링
