Repository Stageus/AIrena-backend, pull requests merged in 2025-02, with the labels that each got.

#1 [SUS-31] Feat/Errocode_401_added
  src/core/error/errorRegistry.ts
Labels: 환경 설정

#2 [SUS-36] 비동기 라우터 만들기 함수 생성
  .vscode/settings.json
  package.json
  src/core/getAsyncRouter/index.ts
  src/router/loginRouter.ts
  src/router/testRouter.ts
  tsconfig.json
Labels: 환경 설정

#3 [SUS-35] 모의고사 생성 API
  .sql/make.sql
  index.ts
  package-lock.json
  package.json
  src/adapter/AIAdapter.ts
  src/adapter/ImageAdapter.ts
  src/adapter/MockAdapter.ts
  src/adapter/OAuthAdapter.ts
  src/core/config/multer.ts
  src/core/config/s3.ts
  src/core/controller/index.ts
  src/core/error/errorRegistry.ts
  src/core/getAsyncRouter/index.ts
  src/core/util/multipartParser.ts
  src/dto/ai/request/GenerateQuizRequestToAI.ts
  src/dto/ai/response/SingleChoiceQuizResponseFromAI.ts
  src/dto/ai/response/TextQuizResponseFromAI.ts
  src/dto/request/MockWriteRequest/MockWriteRequest.ts
  src/dto/response/MockWriteResponse.ts
  src/entity/Image.ts
  src/entity/Mock.ts
  src/entity/Quiz.ts
  src/entity/QuizInfo.ts
  src/repository/ImageRepsitory.ts
  src/repository/MockRepository.ts
  src/router/loginRouter.ts
  src/router/mockRouter.ts
  src/router/testRouter.ts
  src/service/LoginService.ts
  src/service/MockWriteService.ts
  tsconfig.json
Labels: 기능 구현

#5 [SUS-35] 어댑터 위치 변경
  .sql/.sql
  index.ts
  package-lock.json
  package.json
  src/adapter/AIAdapter.ts
  src/adapter/ImageAdapter.ts
  src/adapter/OAuthAdapter.ts
  src/core/config/database/mongoDB.ts
  src/core/config/multer.ts
  src/core/config/postgres.ts
  src/core/config/redis.ts
  src/core/error/CustomError.ts
  src/core/error/errorInfo.ts
  src/core/error/errorRegistry.ts
  src/core/error/globalExceptionHandler.ts
  src/core/util/multipartParser.ts
  src/dto/request/FindPasswordRequest.ts
  src/dto/request/MockWriteRequest.ts
  src/repository/ImageRepository.ts
  src/repository/MemberRepository.ts
  src/repository/MockRepository.ts
  src/repository/testRepository.ts
  src/router/loginRouter.ts
  src/router/memberRouter.ts
  src/router/mockRouter.ts
  src/router/testRouter.ts
  src/service/MemberService.ts
  src/service/MockWriteService.ts
  tsconfig.json
Labels: 기능 구현

#7 [SUS-38] 모의고사 검색
  .sql/.sql
  package-lock.json
  package.json
  src/adapter/AIAdapter.ts
  src/adapter/MockAdapter.ts
  src/core/controller/index.ts
  src/core/error/ErrorInfo.ts
  src/core/error/ErrorRegistry.ts
  src/core/error/globalExceptionHandler.ts
  src/core/util/multipartParser.ts
  src/dto/db/GetLikeDescMockListResultFromDB.ts
  src/dto/frontend/request/FindPasswordRequest.ts
  src/dto/frontend/request/LoginRequest.ts
  src/dto/frontend/request/MockSearchRequest.ts
  src/dto/frontend/request/MockWriteRequest.ts
  src/dto/frontend/request/NicknameChangeRequest.ts
  src/dto/frontend/request/SignupRequest.ts
  src/dto/frontend/request/SignupVerifyRequest.ts
  src/dto/frontend/response/MockSearchResponse.ts
  src/dto/frontend/response/MockWriteResponse.ts
  src/dto/frontend/response/loginUserDataResponse.ts
  src/entity/MockList.ts
  src/repository/MemberRepository.ts
  src/repository/MockRepository.ts
  src/router/loginRouter.ts
  src/router/memberRouter.ts
  src/router/mockRouter.ts
  src/router/testRouter.ts
  src/service/LoginService.ts
  src/service/MemberService.ts
  src/service/MockInfoService.ts
  src/service/MockWriteService.ts
Labels: 기능 구현

#8 [SUS-39] 모의고사 목록 조회 & 모의고사 상세 정보 조회
  .github/workflows/pull-request-ci.yml
  .prettierignore
  src/adapter/MockAdapter.ts
  src/dto/db/MockResultFromDB.ts
  src/dto/db/PaginatedMockListResultFromDB.ts
  src/dto/frontend/request/MockDetailRequest.ts
  src/dto/frontend/request/MockListRequest.ts
  src/dto/frontend/response/MockDeatailResponse.ts
  src/dto/frontend/response/MockListResponse.ts
  src/entity/Mock.ts
  src/entity/MockDetail.ts
  src/entity/MockList.ts
  src/repository/MockRepository.ts
  src/router/mockRouter.ts
  src/service/MockGetService.ts
  src/service/MockInfoService.ts
  src/service/MockWriteService.ts
Labels: 기능 구현

#9 [SUS-37] 비밀번호 변경
  .prettierignore
  package-lock.json
  package.json
  src/core/util/Token.ts
  src/core/util/email/templates/confirmMail.html
  src/dto/frontend/request/NormalLoginRequest.ts
  src/dto/frontend/request/PasswordChangeRequest.ts
  src/dto/frontend/response/FindPasswordResponse.ts
  src/repository/MemberRepository.ts
  src/router/memberRouter.ts
  src/service/MemberService.ts
Labels: 기능 구현

#10 [SUS-43] 모의고사 문제 가져오기 & 모의고사 정답 제출하기 & 모의고사 결과 보기
  .sql/.sql
  src/adapter/AIAdapter.ts
  src/adapter/AnswerSubmitAdapter.ts
  src/adapter/MockAdapter.ts
  src/adapter/MockScoreAdapter.ts
  src/core/error/ErrorRegistry.ts
  src/dto/ai/response/SingleChoiceQuizResponseFromAI.ts
  src/dto/ai/response/TextGradeResponseFromAI.ts
  src/dto/ai/response/TextQuizResponseFromAI.ts
  src/dto/db/AnswerSubmitResultFromDB.ts
  src/dto/db/MockScoreResultFromDB.ts
  src/dto/db/QuizResultFormDB.ts
  src/dto/frontend/request/AnswerSubmitRequest.ts
  src/dto/frontend/request/MockQuizRequest.ts
  src/dto/frontend/response/AnswerSubmitResponse.ts
  src/dto/frontend/response/MockDetailResponse.ts
  src/dto/frontend/response/MockQuizResponse.ts
  src/dto/frontend/response/MockResultResponse.ts
  src/entity/MockScore.ts
  src/entity/MockTextGrade.ts
  src/entity/Quiz.ts
  src/entity/SubmitAnswer.ts
  src/repository/AnswerSubmitRepository.ts
  src/repository/MockRepository.ts
  src/repository/MockScoreRepository.ts
  src/repository/QuizRepository.ts
  src/router/mockRouter.ts
  src/service/AnswerSubmitService.ts
  src/service/MockGetService.ts
  tsconfig.json
Labels: 기능 구현

#18 [SUS-55] 좋아요 API
  .sql/.sql
  index.ts
  package.json
  src/core/error/ErrorRegistry.ts
  src/like/entity/dao/frontend/request/path/ArticleIdxPath.ts
  src/like/repository/LikeHistoryRepository.ts
  src/like/router/addRouter.ts
  src/like/router/deleteRouter.ts
  src/like/router/index.ts
  src/like/service/LikeService.ts
  tsconfig.json
Labels: 기능 구현

#17 [SUS-65] 개인별 모의고사 정보 가져오기
  src/mock/entity/dao/db/IndividualMockDetailResultFromDB.ts
  src/mock/entity/dao/frontend/response/IndividualDetailResponse.ts
  src/mock/repository/MockRepository.ts
  src/mock/router/mockItemRouter.ts
  src/mock/service/MockItemService.ts
Labels: 기능 구현

#19 [SUS-54] 공지사항
  index.ts
  package-lock.json
  package.json
  src/core/config/postgres.ts
  src/core/controller/module/checkAuthReturningUserId.ts
  src/core/error/ErrorRegistry.ts
  src/mock/service/ListService.ts
  src/notice/entity/dao/frontend/request/ListRequest.ts
  src/notice/entity/dao/frontend/request/ListSearchRequest.ts
  src/notice/entity/dao/frontend/request/NoticeEditBodyRequest.ts
  src/notice/entity/dao/frontend/request/NoticePathRequest.ts
  src/notice/entity/dao/frontend/request/WriteRequest.ts
  src/notice/entity/dao/frontend/response/ListResponse.ts
  src/notice/entity/dao/frontend/response/ListSearchResponse.ts
  src/notice/entity/dao/frontend/response/NoticeResponse.ts
  src/notice/entity/dao/frontend/response/WriteResponse.ts
  src/notice/entity/dto/NoticeList.ts
  src/notice/repository/NoticeRepository.ts
  src/notice/router/index.ts
  src/notice/router/listRouter.ts
  src/notice/router/noticeItemRouter.ts
  src/notice/router/writeRouter.ts
  src/notice/service/ListService.ts
  src/notice/service/NoticeItemService.ts
  src/notice/service/WriteService.ts
Labels: 기능 구현

#21 [SUS-68] 리팩토링 완료
  src/mock/entity/dao/frontend/response/ListResponse.ts
  src/mock/entity/dto/MockList.ts
  src/mock/service/ListService.ts
  src/notice/entity/dao/frontend/response/ListResponse.ts
  src/notice/entity/dao/frontend/response/ListSearchResponse.ts
  src/notice/entity/dto/NoticeList.ts
  src/notice/repository/NoticeRepository.ts
  src/notice/service/ListService.ts
Labels: 리팩터링

#20 [SUS-66] 랭킹
  index.ts
  package.json
  src/rank/entity/dao/request/FilteredRankListRequest.ts
  src/rank/entity/dao/request/RankListRequest.ts
  src/rank/entity/dao/response/FilteredRankListResponse.ts
  src/rank/entity/dao/response/RankListResponse.ts
  src/rank/entity/dto/RankList.ts
  src/rank/repository/rankListRepository.ts
  src/rank/router/index.ts
  src/rank/router/rankListRouter.ts
  src/rank/service/rankListService.ts
  tsconfig.json
Labels: 기능 구현

#22 [SUS-68] 공지사항 검색 API 수정
  src/notice/entity/dto/NoticeList.ts
  src/notice/repository/NoticeRepository.ts
  src/notice/service/ListService.ts
Labels: 기능 구현, 리팩터링

#23 [SUS 48] 비밀번호 암호화
  package-lock.json
  package.json
  src/member/service/LoginService.ts
  src/member/service/SignupService.ts
Labels: 기능 구현, 리팩터링
